services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command: ["start-dev", "--import-realm"]   # dev mode + auto-import JSON from /opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"           # Keycloak on http://localhost:8081
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
